### PR TITLE
Upgrade to Bazel 4.0.0

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
This is the latest LTS release if I understand
https://blog.bazel.build/2020/11/10/long-term-support-release.html
correctly. Also, it is the last version that supports `rbe_autoconfig`.
I'm not really sure what we're going to have to do without that :-/

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Need to install the latest bazel version on the CI machine. Should really get around to dockerizing that...

**Review by kuhar — APPROVED** [review]

**Comment by chandlerc** [comment]
Not sure if you were looking for review but LGTM...

**Comment by chandlerc** [comment]
> Not sure if you were looking for review but LGTM...

Sorry for the noise here, the mobile app somehow didn't show the other activity on this thread so I didn't realize this had already been reviewed.... Very sorry for that!

**Comment by GMNGeoffrey** [comment]
I didn't know there even was an app. I guess this hasn't really been much
of an endorsement of it though 😁

**Pull request merged**
