### PR TITLE
Integrate LLVM at llvm/llvm-project@8854b27b198c

### PR DESCRIPTION
**Pull request by hanhanW**
Update BUILD files and submodule for
[8854b27b198c](https://github.com/llvm/llvm-project/commit/8854b27b198c)

### CODE REVIEW

**Comment by rsuderman** [comment]
Looks like there are build errors that need to be fixed.

**Comment by GMNGeoffrey** [comment]
I'll send a PR

**Comment by hanhanW** [comment]
> I'll send a PR

thanks!

**Comment by GMNGeoffrey** [comment]
Taking a while... There's some new Cuda stuff :-/

**Pull request closed without merging**
