### PR TITLE
Update to llvm/llvm-project@499bce3abab8

### PR DESCRIPTION
**Pull request by mihaimaruseac**

### CODE REVIEW

**Review by GMNGeoffrey — APPROVED** [review]
Thanks! Can you confirm that you've tested this locally?

**Comment by GMNGeoffrey** [comment]
We can ignore the status checks here. They shouldn't be triggering on this PR at all. I just tweaked the  BuildKite pipeline in a way that hopefully it should stop doing that. The GitHub actions workflow is already deleted on the main branch. Really having this in a separate branch of the same repo is a hack, so not quite sure how to get it to behave.

**Comment by mihaimaruseac** [comment]
I ran `bazel build --config=generic_clang @llvm-project//llvm:NVPTXCodeGen` (since that was the target failing in TF).

Running `bazel build --config=generic_clang @llvm-project//...` fails on my end

```
ERROR: /usr/local/google/home/mihaimaruseac/.cache/bazel/_bazel_mihaimaruseac/72d11c4dfc9b1a3c3ec48afbb7d953e7/external/llvm-project/llvm/BUILD:3395:1: in binary_alias rule @llvm-project//llvm:llvm-addr2line: 
Traceback (most recent call last):
        File "/usr/local/google/home/mihaimaruseac/.cache/bazel/_bazel_mihaimaruseac/72d11c4dfc9b1a3c3ec48afbb7d953e7/external/llvm-project/llvm/BUILD", line 3395
                binary_alias(name = 'llvm-addr2line')
        File "/usr/local/google/home/mihaimaruseac/.cache/bazel/_bazel_mihaimaruseac/72d11c4dfc9b1a3c3ec48afbb7d953e7/external/llvm-project/llvm/binary_alias.bzl", line 14, in _binary_alias_impl
                ctx.actions.symlink(<3 more arguments>)
symlink() got unexpected keyword argument 'target_file'
INFO: Repository remote_coverage_tools instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /usr/local/google/home/mihaimaruseac/.cache/bazel/_bazel_mihaimaruseac/72d11c4dfc9b1a3c3ec48afbb7d953e7/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
ERROR: Analysis of target '@llvm-project//llvm:llvm-addr2line' failed; build aborted: Analysis of target '@llvm-project//llvm:llvm-addr2line' failed
INFO: Elapsed time: 5.433s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (26 packages loaded, 9322 targets configured)
```

**Comment by GMNGeoffrey** [comment]
Are you running with an old version of Bazel? Looks like the API was finalized in 3.2

https://docs.bazel.build/versions/3.1.0/skylark/lib/actions.html#symlink
vs
https://docs.bazel.build/versions/3.2.0/skylark/lib/actions.html#symlink

If you're running the demo, the `.bazelversion` should ensure that it's 3.3.1

**Comment by mihaimaruseac** [comment]
Oh, I'm using TF's Bazel, 3.1.

Let me upgrade.

**Comment by mihaimaruseac** [comment]
With Bazel 3.7 it is building

```
INFO: Elapsed time: 1246.247s, Critical Path: 171.34s
INFO: 10641 processes: 2157 internal, 8484 linux-sandbox.
INFO: Build completed successfully, 10641 total actions
```

**Comment by GMNGeoffrey** [comment]
Thanks!

**Pull request merged**
