### PR TITLE
Integrate LLVM at llvm/llvm-project@418c21

### PR DESCRIPTION
**Pull request by rsuderman**
Update BUILD files and submodule for
[418c21](https://github.com/llvm/llvm-project/commit/418c218efa95)

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
Ah lemme fix the config diff thing. One sec

**Comment by rsuderman** [comment]
I thought I just handled it in the new push but apparently not?

**Comment by GMNGeoffrey** [comment]
> I thought I just handled it in the new push but apparently not?

We need to actually update the configs to properly set that :-) The test is literally just a change detector to say "hey this thing changed"

**Review by GMNGeoffrey — APPROVED** [review]
Okie dokie. Our current runners do not have `mallinfo2`, so we don't want to set that. At some point, of course, we should make this actually configurable, but this is right for now

**Pull request merged**
