### PR TITLE
Disallow more empty test globs

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
Apparently I messed up my regex and missed a bunch of these in
https://github.com/google/llvm-bazel/pull/121/

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
@rupprecht if you could take a look

**Comment by rupprecht** [comment]
It doesn't look like buildozer has a command that can set attributes like this, so regex it is.

Not sure what regex you're using, but I think this should be safe to automate, if you'd like to try this for more BUILD files:

`sed -i '/allow_empty = False/d; s/glob(/glob(allow_empty=False,/'  clang/unittests/BUILD && buildifier -a -v`

**Comment by GMNGeoffrey** [comment]
> It doesn't look like buildozer has a command that can set attributes like this, so regex it is.
> 
> Not sure what regex you're using, but I think this should be safe to automate, if you'd like to try this for more BUILD files:
> 
> `sed -i '/allow_empty = False/d; s/glob(/glob(allow_empty=False,/' clang/unittests/BUILD && buildifier -a -v`

It's a bit more complicated because include is a positional argument and has to come first. I think I screwed up the multiline match the first time I did it. I got one that worked now though

**Comment by rupprecht** [comment]
> It's a bit more complicated because include is a positional argument and has to come first

Making the substitution `s/glob(/glob(allow_empty=False,/` indeed breaks that, but running buildifier should restore it to the right place IIUC. However, it doesn't remove duplicate `allow_empty = False` entries, so the initial `/allow_empty = False/d;` is needed to clear that out.

**Review by rupprecht — APPROVED** [review]

**Comment by GMNGeoffrey** [comment]
> > It's a bit more complicated because include is a positional argument and has to come first
> 
> Making the substitution `s/glob(/glob(allow_empty=False,/` indeed breaks that, but running buildifier should restore it to the right place IIUC. However, it doesn't remove duplicate `allow_empty = False` entries, so the initial `/allow_empty = False/d;` is needed to clear that out.

Ah you're right, buildifier does fix that, nice! I think your other command would delete the whole line, which could have other stuff, but `s/allow_empty=False,\?//` should do it :-)

**Pull request merged**
